# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

before_install:
#  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - curl -OL http://raw.github.com/lcolladotor/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_bioc_deps

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

after_script:
  - ./travis-tool.sh dump_logs_by_extension "timings"
  - ./travis-tool.sh dump_sysinfo

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: e1atKdlUJfaP8iL09yPiTi8N9tt/kX7wGk9VvSppTn2sh9mB2uD9PkXh/qBR8EYXIyaKTftzhnOTocey94bRDPZKeFUlGxo609GNwYxY7RC9a1SKs4heC13QEolq1x0YmW/0sr+PdjmQCNrIBLpvLgOStMGP1wKeurlb6aHea7M=

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual --no-resave-data"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
    - R_CHECK_TIME="TRUE"
    - _R_CHECK_TIMINGS_="0"
